language: python
python:
    "3.6"
install:
     "pip install -r requirements.txt"   
script:
     - "python tests/test_useraccount.py"
     - "coverage run app/useraccount.py"
after_success: coveralls
